#!/bin/sh

sxhkd &
bspc monitor -d I II III IV V &
picom &
feh --bg-scale ~/Downloads/ghost-minimal-4k-l7.png &
~/.config/polybar/launch.sh &

bspc config border_width         1
bspc config window_gap           20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"









